from schemas.review import ReviewFinding


def format_review_comment(findings: list[ReviewFinding]) -> str:
    if not findings:
        return (
            "## 🤖 Agentic Code Review\n\n"
            "✅ No security, error-handling, or testing issues found."
        )

    lines = [
        "## 🤖 Agentic Code Review",
        "",
        f"Found **{len(findings)} issue(s)** in this pull request.",
        "",
    ]

    for index, finding in enumerate(findings, start=1):
        lines.extend(
            [
                f"### {index}. {finding.severity} — {finding.category}",
                "",
                f"**File:** `{finding.file}`  ",
                f"**Line:** `{finding.line}`",
                "",
                f"**Issue:** {finding.issue}",
                "",
                f"**Why it matters:** {finding.explanation}",
                "",
                f"**Suggested fix:** {finding.suggested_fix}",
                "",
                "---",
                "",
            ]
        )

    lines.extend(
        [
            "Generated by the **Agentic Code Reviewer**.",
        ]
    )

    return "\n".join(lines)
